default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ieat_dev

test:
  <<: *default
  database: ieat_tester

production:
  <<: *default
  database: ieat_produc
  username: ieat
  password: <%= ENV['IEAT_DATABASE_PASSWORD'] %>
